### ISSUE TITLE
Gii Model builder fails

### ISSUE THREAD

**Issue by bmartinGithub** [edgardmessias/yiinformix#3]
I'm not sure what was causing the Gii model builder to fail when using yiinformix, It just returned an empty screen. Creating the Model by hand worked so the rest of the Gii crud generators would work.

**Comment by edgardmessias** [comment]
how many tables your own system?

**Comment by bmartinGithub** [comment]
Approximately 1380 tables not including sys tables.

**Comment by edgardmessias** [comment]
I know this problem, and it is unfortunately how it works GII.
Try enabling schema cache and reload the page several times
